### ISSUE TITLE
issue in Firefox not identifying download resources in certain videos

### ISSUE THREAD

**Issue by mhanor** [feller-prj/extractor-project#26]
Hi,

I'm having trouble on some YouTube videos, download links don't show up correctly (only options such as tiny - undefinedK). Here's an example of such a link:
https://www.youtube.com/watch?v=MyJVcLDmt2c
This might be caused by the upgrade to Firefox 76.0 (Windows 10 1903 64 bit). I've upgraded the native client to 0.8.8. There are some errors in the browser console console when clicking the extension in-page button, see the attached file:
[console-export-2020-5-8_10-10-34.txt](https://github.com/feller-prj/extractor-project/files/4597511/console-export-2020-5-8_10-10-34.txt)

Kind regards,
Mihai

**Comment by github-thecat** [comment]
I have the same issue starting from today on all videos.
Yesterday it was working fine.
I have Firefox 75.0 (64-bit) on macOS 10.14.6 and I haven't done any updates (Firefox, macOS, ...) since yesterday.
YouTube has probably changed something.

Best regards.
And thanks a lot for this great extension.

**Comment by powerfrontier** [comment]
Same problem here just after upgrade to Firefox 76

**Comment by mhanor** [comment]
I believe this is fixed.
